- hosts: localhost
  become: true
   
  vars:
    jenkins_hostname: localhost
    java_packages:
      - openjdk-21-jdk

    jenkins_plugins: []
    docker_install_compose_plugin: true
    pip_install_packages:
      - name: docker

  pre_tasks:
  - name: update all packages 
    ansible.builtin.apt:
      name: '*'
      #update_only: yes
      update_cache: yes
      state: latest 

  #- name: Install epel release
  #  yum: 
  #    name: epel-release
  #    state: installed
  

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: geerlingguy.java
    - role: geerlingguy.jenkins